#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  eyesin,         sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           klesh,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ruka,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moving(int VL, int VR, int time){
	motor[port1]=VL;
	motor[port10]=VR;
	wait1Msec(time);
}

void updown(int VU, int time)
{
	motor[port7]=VU;
	wait1Msec(time);
}

void hand(int VH, int time)
{
	motor[port6]=VH;
	wait1Msec(time);
}

void arm()
{
	int t = 100000;
	resetMotorEncoder(ruka);
  while (t > 0)
  {
  	if (nMotorEncoder(ruka) < 180)
  		motor[ruka] = 20;
  	else
  		motor[ruka] = -20;
  	t -= 1;
  }
}


void stena()
{	int v = 25;
	int t = 1;
	int time = 0;
	while(t)
	{
	if (SensorValue[dgtl1]<20)
		{
			t = 0;
			motor[port1]=0;
			motor[port10]=0;
			updown(-100, 550);
			hand(50, 1000);
			updown(150, 500);
			arm();
			if(v == 25){
				moving(100, -100, 1000);
			}
		}
	else
		{
		moving(v, v, 50);
		if (v == 25){
			time += 50;
		}
		if (v == -25){
			time -= 50;
		}
		}
	}
}

task main()
{
	stena();
}


wait1Msec(2000);
	while (true){
	if(SensorValue[SonarSensor] > 10){
	motor[left] = 0;
	motor[right] = 0;

	}
	else{
		motor[left] = -25;
		motor[right] = 25;
	}
}
